basePath: /
definitions:
  service.BatchCount:
    properties:
      total_batches:
        type: integer
    type: object
  service.DailySubmissions:
    properties:
      day:
        type: integer
      submissions:
        type: integer
    type: object
  service.EligibleNodes:
    properties:
      day:
        type: integer
      eligible_nodes_count:
        type: integer
      slot_ids:
        items:
          type: string
        type: array
    type: object
  service.EligibleNodesRequest:
    properties:
      data_market_address:
        type: string
      epoch_id:
        type: integer
      past_days:
        type: integer
      token:
        type: string
    type: object
  service.EligibleSubmissionCounts:
    properties:
      count:
        type: integer
      slot_id:
        type: integer
    type: object
  service.EligibleSubmissionCountsResponse:
    properties:
      eligible_submission_counts:
        items:
          $ref: '#/definitions/service.EligibleSubmissionCounts'
        type: array
    type: object
  service.EpochDataMarketDayRequest:
    properties:
      data_market_address:
        type: string
      day:
        type: integer
      epoch_id:
        type: integer
      token:
        type: string
    type: object
  service.EpochDataMarketRequest:
    properties:
      data_market_address:
        type: string
      epoch_id:
        type: integer
      token:
        type: string
    type: object
  service.InfoType-service_BatchCount:
    properties:
      response:
        $ref: '#/definitions/service.BatchCount'
      success:
        type: boolean
    type: object
  service.InfoType-service_EligibleSubmissionCountsResponse:
    properties:
      response:
        $ref: '#/definitions/service.EligibleSubmissionCountsResponse'
      success:
        type: boolean
    type: object
  service.InfoType-service_ResponseArray-service_DailySubmissions:
    properties:
      response:
        items:
          $ref: '#/definitions/service.DailySubmissions'
        type: array
      success:
        type: boolean
    type: object
  service.InfoType-service_ResponseArray-service_EligibleNodes:
    properties:
      response:
        items:
          $ref: '#/definitions/service.EligibleNodes'
        type: array
      success:
        type: boolean
    type: object
  service.Response-service_BatchCount:
    properties:
      info:
        $ref: '#/definitions/service.InfoType-service_BatchCount'
      request_id:
        type: string
    type: object
  service.Response-service_EligibleSubmissionCountsResponse:
    properties:
      info:
        $ref: '#/definitions/service.InfoType-service_EligibleSubmissionCountsResponse'
      request_id:
        type: string
    type: object
  service.Response-service_ResponseArray-service_DailySubmissions:
    properties:
      info:
        $ref: '#/definitions/service.InfoType-service_ResponseArray-service_DailySubmissions'
      request_id:
        type: string
    type: object
  service.Response-service_ResponseArray-service_EligibleNodes:
    properties:
      info:
        $ref: '#/definitions/service.InfoType-service_ResponseArray-service_EligibleNodes'
      request_id:
        type: string
    type: object
  service.SubmissionsRequest:
    properties:
      data_market_address:
        type: string
      past_days:
        type: integer
      slot_id:
        type: integer
      token:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.yoursupport.com
  description: This API handles submissions and provides Swagger documentation
  termsOfService: http://yourterms.com
  title: My API Documentation
  version: "1.0"
paths:
  /batchCount:
    post:
      consumes:
      - application/json
      description: Retrieves the total number of batches created within a specific
        epoch for a given data market address
      parameters:
      - description: Epoch data market request payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.EpochDataMarketRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response-service_BatchCount'
        "400":
          description: 'Bad Request: Invalid input parameters (e.g., missing or invalid
            epochID, or invalid data market address)'
          schema:
            type: string
        "401":
          description: 'Unauthorized: Incorrect token'
          schema:
            type: string
      summary: Get total batch count
      tags:
      - Batch Count
  /eligibleNodesCount:
    post:
      consumes:
      - application/json
      description: Retrieves the total count of eligible nodes along with their corresponding
        slotIDs for a specified data market address and epochID across a specified
        number of past days
      parameters:
      - description: Eligible nodes count payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.EligibleNodesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response-service_ResponseArray-service_EligibleNodes'
        "400":
          description: 'Bad Request: Invalid input parameters (e.g., past days < 1,
            missing or invalid epochID, or invalid data market address)'
          schema:
            type: string
        "401":
          description: 'Unauthorized: Incorrect token'
          schema:
            type: string
      summary: Get eligible nodes count
      tags:
      - Eligible Nodes Count
  /eligibleSlotSubmissionCount:
    post:
      consumes:
      - application/json
      description: Retrieves the submission counts of all eligible slotIDs within
        a specific epoch for a given data market address
      parameters:
      - description: Epoch data market day request payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.EpochDataMarketDayRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response-service_EligibleSubmissionCountsResponse'
        "400":
          description: 'Bad Request: Invalid input parameters (e.g., missing or invalid
            epochID, invalid day or invalid data market address)'
          schema:
            type: string
        "401":
          description: 'Unauthorized: Incorrect token'
          schema:
            type: string
      summary: Get the submission counts of all eligible slotIDs
      tags:
      - Eligible Submission Count
  /eligibleSubmissions:
    post:
      consumes:
      - application/json
      description: Retrieves eligible submission counts for a specific data market
        address across a specified number of past days
      parameters:
      - description: Submissions request payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.SubmissionsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response-service_ResponseArray-service_DailySubmissions'
        "400":
          description: 'Bad Request: Invalid input parameters (e.g., past days < 1,
            invalid slotID or invalid data market address)'
          schema:
            type: string
        "401":
          description: 'Unauthorized: Incorrect token'
          schema:
            type: string
      summary: Get eligible submissions
      tags:
      - Submissions
  /totalEligibleSubmissions:
    post:
      consumes:
      - application/json
      description: Retrieves total eligible submission counts for a specific data
        market address across a specified number of past days
      parameters:
      - description: Submissions request payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.SubmissionsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response-service_ResponseArray-service_DailySubmissions'
        "400":
          description: 'Bad Request: Invalid input parameters (e.g., past days < 1,
            invalid slotID or invalid data market address)'
          schema:
            type: string
        "401":
          description: 'Unauthorized: Incorrect token'
          schema:
            type: string
      summary: Get total eligible submissions
      tags:
      - Submissions
  /totalSubmissions:
    post:
      consumes:
      - application/json
      description: Retrieves total submission counts for a specific data market address
        across a specified number of past days
      parameters:
      - description: Submissions request payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.SubmissionsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response-service_ResponseArray-service_DailySubmissions'
        "400":
          description: 'Bad Request: Invalid input parameters (e.g., past days < 1,
            invalid slotID or invalid data market address)'
          schema:
            type: string
        "401":
          description: 'Unauthorized: Incorrect token'
          schema:
            type: string
      summary: Get total submissions
      tags:
      - Submissions
swagger: "2.0"
