basePath: /
definitions:
  service.DailySubmissions:
    properties:
      day:
        type: integer
      submissions:
        type: integer
    type: object
  service.InfoType-service_ResponseArray-service_DailySubmissions:
    properties:
      response:
        items:
          $ref: '#/definitions/service.DailySubmissions'
        type: array
      success:
        type: boolean
    type: object
  service.Response-service_ResponseArray-service_DailySubmissions:
    properties:
      info:
        $ref: '#/definitions/service.InfoType-service_ResponseArray-service_DailySubmissions'
      request_id:
        type: string
    type: object
  service.SubmissionsRequest:
    properties:
      data_market_address:
        type: string
      past_days:
        type: integer
      slot_id:
        type: integer
      token:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.yoursupport.com
  description: This API handles submissions and provides Swagger documentation
  termsOfService: http://yourterms.com
  title: My API Documentation
  version: "1.0"
paths:
  /totalSubmissions:
    post:
      consumes:
      - application/json
      description: Retrieves total submission counts for a specific data market address
        across a specified number of past days
      parameters:
      - description: Submissions request payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.SubmissionsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Response-service_ResponseArray-service_DailySubmissions'
        "400":
          description: Bad Request, past days less than 1, invalid slotID or invalid
            data market address
          schema:
            type: string
        "401":
          description: 'Unauthorized: Incorrect token'
          schema:
            type: string
      summary: Get total submissions
      tags:
      - Submissions
swagger: "2.0"
